- job:
    name: monasca-tempest-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/monasca-tempest-base/run.yaml
    post-run: playbooks/legacy/monasca-tempest-base/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/monasca-agent
      - openstack/monasca-api
      - openstack/monasca-common
      - openstack/monasca-grafana-datasource
      - openstack/monasca-notification
      - openstack/monasca-persister
      - openstack/monasca-statsd
      - openstack/monasca-thresh
      - openstack/monasca-ui
      - openstack/python-monascaclient
      - openstack/tempest
      - openstack/monasca-tempest-plugin

- job:
    name: monasca-tempest-python-mysql
    parent: monasca-tempest-base
    vars:
      database: mysql
      tsdb: influxdb
      api_lang: python
      persister_lang: python

- job:
    name: monasca-tempest-python-postgresql
    parent: monasca-tempest-base
    vars:
      database: postgresql
      tsdb: influxdb
      api_lang: python
      persister_lang: python
    voting: false

- job:
    name: monasca-tempest-java-mysql
    parent: monasca-tempest-base
    vars:
      database: mysql
      tsdb: influxdb
      api_lang: java
      persister_lang: java

- job:
    name: monasca-tempest-java-postgresql
    parent: monasca-tempest-base
    vars:
      database: postgresql
      tsdb: influxdb
      api_lang: java
      persister_lang: java
    voting: false

- job:
    name: monasca-tempest-python-cassandra
    parent: monasca-tempest-base
    vars:
      database: mysql
      tsdb: cassandra
      api_lang: python
      persister_lang: python

- job:
    name: monasca-tempest-java-cassandra
    parent: monasca-tempest-base
    vars:
      database: mysql
      tsdb: cassandra
      api_lang: python
      persister_lang: java

- project:
    name: openstack/monasca-api
    check:
      jobs:
        - monasca-tempest-python-mysql
        - monasca-tempest-python-postgresql
        - monasca-tempest-java-mysql
        - monasca-tempest-java-postgresql
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
    gate:
      jobs:
        - monasca-tempest-python-mysql
        - monasca-tempest-java-mysql
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
