#!/bin/sh

case "$1" in
  configure)
    if ! [ `getent passwd monasca_api` ]; then
      adduser --system --group monasca_api
    fi

    #Restart does not pick up upstart job config changes stop/start is needed
    stop monasca-api
    start monasca-api
  ;;
esac

exit 0
