#!/bin/sh

case "$1" in
  configure)
    if ! [ `getent passwd mon_api` ]; then
      adduser --system --group mon_api
    fi

    #Restart does not pick up upstart job config changes stop/start is needed
    stop mon-api
    start mon-api
  ;;
esac

exit 0
